import axios from "axios";

import {
  AuthResponse,
  Staff,
  Ticket,
  Role,
  Department,
  Company,
  Branch,
  Appraisal,
} from "@/app/types";

const API_URL = process.env.NEXT_PUBLIC_API_URL;

const api = axios.create({
  baseURL: API_URL,
  headers: {
    "Content-Type": "application/json",
  },
});

// Helper to extract the actual data payload from various backend response shapes
const extractData = (
  res: any,
  keys: string[] = [
    "data",
    "users",
    "staff",
    "tickets",
    "departments",
    "companies",
    "branches",
    "employees",
    "logs",
    "items",
  ],
) => {
  if (!res) return null;
  // If it's the axios response object, look at response.data
  const body = res.data !== undefined ? res.data : res;

  if (Array.isArray(body)) return body;
  if (!body || typeof body !== "object") return body;

  // Check for success/status patterns and common keys
  for (const key of keys) {
    if (Array.isArray(body[key])) return body[key];
    if (body[key] && typeof body[key] === "object") {
      // Handle deeper nesting like { status: 'success', data: { logs: [...] } }
      if (key === "data") {
        for (const subKey of keys) {
          if (Array.isArray(body.data[subKey])) return body.data[subKey];
        }
      }
      return body[key];
    }
  }

  return body;
};

// Add interceptor to attach token and handle FormData properly
api.interceptors.request.use((config) => {
  if (typeof window !== "undefined") {
    const token = localStorage.getItem("token");
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }

    // If we are sending FormData (like a file upload), we MUST NOT set the Content-Type header manually.
    // It needs to be generated by the browser to include the 'boundary' string.
    // Since we have a default 'application/json' set globally, we explicitly delete it here for FormData.
    if (config.data instanceof FormData) {
      delete config.headers["Content-Type"];
    }
  }
  return config;
});

export const authApi = {
  login: async (email: string, password: string): Promise<AuthResponse> => {
    try {
      const response = await api.post("api/auth/login", { email, password });
      return response.data;
    } catch (e) {
      throw e;
    }
  },
};

export const staffApi = {
  getAll: async (): Promise<Staff[]> => {
    try {
      const response = await api.get("api/lookups/users?limit=100");
      return extractData(response) || [];
    } catch (e) {
      throw e;
    }
  },
  getById: async (id: string): Promise<Staff> => {
    try {
      const response = await api.get(`api/lookups/users/${id}`);
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  getMe: async (): Promise<Staff> => {
    try {
      const response = await api.get("api/lookups/users/me");
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  getByDepartment: async (departmentId: string): Promise<Staff[]> => {
    try {
      const response = await api.get(
        `api/lookups/users?department_id=${departmentId}`,
      );
      const users: Staff[] = extractData(response) || [];

      // Client-side filtering to ensure accuracy (API might ignore param and return all users)
      return users.filter((user) => {
        const uDeptId =
          user.department_id ||
          (typeof user.department === "object" && user.department
            ? (user.department as any)._id || (user.department as any).id
            : null);

        const uDeptString =
          typeof user.department === "string" ? user.department : "";

        return uDeptId == departmentId || uDeptString == departmentId;
      });
    } catch (e) {
      console.error(`Failed to fetch staff for department ${departmentId}`, e);
      return [];
    }
  },
  create: async (staffData: Partial<Staff>): Promise<any> => {
    try {
      const response = await api.post("api/auth/register", staffData);
      return response.data;
    } catch (e) {
      throw e;
    }
  },
  update: async (id: string, staffData: Partial<Staff>): Promise<any> => {
    try {
      console.log(`Updating staff at path: api/auth/update/${id}`);
      const response = await api.put(`api/auth/update/${id}`, staffData);
      return response.data;
    } catch (e) {
      throw e;
    }
  },
  delete: async (id: string): Promise<any> => {
    try {
      const response = await api.delete(`api/auth/${id}`);
      return response.data;
    } catch (e) {
      throw e;
    }
  },
};

export const attendanceApi = {
  getAll: async (): Promise<any> => {
    try {
      const response = await api.get("api/attendance/status");
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  getByStaffId: async (staffId: string): Promise<any> => {
    try {
      const response = await api.get(
        `api/attendance/metrics?userId=${staffId}&limit=100`,
      );
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  clockIn: async (userId: string): Promise<any> => {
    try {
      const response = await api.post("api/attendance/clock-in", { userId });
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  clockOut: async (userId: string): Promise<any> => {
    try {
      const response = await api.post("api/attendance/clock-out", { userId });
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  adminClockInUser: async (
    userId: string,
    override_reason: string,
  ): Promise<any> => {
    try {
      const response = await api.post("api/attendance/admin/clock-in-user", {
        userId,
        override_reason,
      });
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
};

export const ticketApi = {
  getAll: async (page = 1, limit = 10): Promise<any> => {
    try {
      const response = await api.get(`api/tickets?page=${page}&limit=${limit}`);
      const data = extractData(response) || [];
      const total = response.data?.total || data.length;
      return { data, total };
    } catch (e) {
      throw e;
    }
  },
  getById: async (id: string): Promise<any> => {
    try {
      const response = await api.get(`api/tickets/${id}`);
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  create: async (ticketData: Partial<Ticket>): Promise<any> => {
    try {
      const response = await api.post("api/tickets", ticketData);
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  respond: async (
    ticketId: string,
    actionData: {
      action: "ACKNOWLEDGE" | "CONTEST" | "RESOLVE" | "VOID";
      contest_note?: string;
      contest_image?: File;
    },
  ): Promise<any> => {
    try {
      // If there is an image, we need FormData
      if (actionData.contest_image) {
        const formData = new FormData();
        formData.append("action", actionData.action);
        if (actionData.contest_note)
          formData.append("contest_note", actionData.contest_note);
        formData.append("contest_image", actionData.contest_image);
        const response = await api.patch(
          `api/tickets/${ticketId}/respond`,
          formData,
          {
            headers: { "Content-Type": "multipart/form-data" },
          },
        );
        return extractData(response);
      }

      const response = await api.patch(
        `api/tickets/${ticketId}/respond`,
        actionData,
      );
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  delete: async (id: string): Promise<any> => {
    try {
      const response = await api.delete(`api/tickets/${id}`);
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
};

export const lookupApi = {
  getRoles: async (): Promise<Role[]> => {
    try {
      const response = await api.get("api/lookups/roles");
      return extractData(response) || [];
    } catch (e) {
      throw e;
    }
  },
  getDepartments: async (): Promise<Department[]> => {
    try {
      const response = await api.get("api/lookups/departments");
      return extractData(response) || [];
    } catch (e) {
      throw e;
    }
  },
};

export const departmentApi = {
  create: async (departmentData: Partial<Department>): Promise<any> => {
    try {
      const response = await api.post("api/departments", departmentData);
      return extractData(response);
    } catch (e: any) {
      throw e;
    }
  },
  getAll: async (): Promise<Department[]> => {
    try {
      const response = await api.get("api/departments");
      return extractData(response) || [];
    } catch (e) {
      throw e;
    }
  },
  getById: async (id: string): Promise<Department> => {
    try {
      const response = await api.get(`api/departments/${id}`);
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
};

export const companyApi = {
  create: async (companyData: Partial<Company> | FormData): Promise<any> => {
    try {
      const isFormData =
        typeof window !== "undefined" && companyData instanceof FormData;
      const response = await api.post("api/companies", companyData, {
        headers: isFormData ? { "Content-Type": undefined } : {},
      });
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  getAll: async (): Promise<Company[]> => {
    try {
      const response = await api.get("api/companies");
      return extractData(response) || [];
    } catch (e) {
      throw e;
    }
  },
  getEmployees: async (companyId: string): Promise<Staff[]> => {
    try {
      const response = await api.get(`api/companies/${companyId}/employees`);
      return extractData(response) || [];
    } catch (e) {
      console.error("Failed to fetch company employees:", e);
      return [];
    }
  },
  delete: async (id: string): Promise<any> => {
    try {
      const response = await api.delete(`api/companies/${id}`);
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
};

export const branchApi = {
  create: async (branchData: Partial<Branch>): Promise<any> => {
    try {
      const response = await api.post("api/branches", branchData);
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  getAll: async (): Promise<Branch[]> => {
    try {
      const response = await api.get("api/branches");
      return extractData(response) || [];
    } catch (e) {
      throw e;
    }
  },
  getById: async (id: string): Promise<Branch> => {
    try {
      const response = await api.get(`api/branches/${id}`);
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
  delete: async (id: string): Promise<any> => {
    try {
      const response = await api.delete(`api/branches/${id}`);
      return extractData(response);
    } catch (e) {
      throw e;
    }
  },
};

export const appraisalApi = {
  getMonthly: async (
    userId: string,
    month: string | number,
    year: string | number,
  ): Promise<Appraisal[]> => {
    try {
      const response = await api.get(`api/appraisals/user/${userId}`, {
        params: { month, year },
      });
      return extractData(response) || [];
    } catch (e) {
      console.error("Failed to fetch appraisals:", e);
      throw e;
    }
  },
};

export default api;
