import axios from 'axios';

import { AuthResponse, Staff, Ticket, Role, Department, Company, Branch, Appraisal } from '@/app/types';

const API_URL = process.env.NEXT_PUBLIC_API_URL;

const api = axios.create({
    baseURL: API_URL,
    headers: {
        'Content-Type': 'application/json',
    },
});

// Add interceptor to attach token and handle FormData properly
api.interceptors.request.use((config) => {
    if (typeof window !== 'undefined') {
        const token = localStorage.getItem('token');
        if (token) {
            config.headers.Authorization = `Bearer ${token}`;
        }

        // If we are sending FormData (like a file upload), we MUST NOT set the Content-Type header manually.
        // It needs to be generated by the browser to include the 'boundary' string.
        // Since we have a default 'application/json' set globally, we explicitly delete it here for FormData.
        if (config.data instanceof FormData) {
            delete config.headers['Content-Type'];
        }
    }
    return config;
});

export const authApi = {
    login: async (email: string, password: string): Promise<AuthResponse> => {
        try {
            const response = await api.post('api/auth/login', { email, password });
            return response.data;
        } catch (e) {
            throw e;
        }
    },
};

export const staffApi = {
    getAll: async (): Promise<Staff[]> => {
        try {
            const response = await api.get('api/lookups/users');
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    getById: async (id: string): Promise<Staff> => {
        try {
            const response = await api.get(`api/lookups/users/${id}`);
            const data = response.data;
            // Defensive check: handle nested data or user property
            if (data && typeof data === 'object' && data.data) {
                return data.data;
            } else if (data && typeof data === 'object' && data.user) {
                return data.user;
            }
            return data;
        } catch (e) {
            throw e;
        }
    },
    getMe: async (): Promise<Staff> => {
        try {
            const response = await api.get('api/lookups/users/me');
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    getByDepartment: async (departmentId: string): Promise<Staff[]> => {
        try {
            console.log(`API Call: api/lookups/users?department_id=${departmentId}`);
            const response = await api.get(`api/lookups/users?department_id=${departmentId}`);
            const data = response.data;
            console.log(`Response for dept ${departmentId}:`, Array.isArray(data) ? `Array(${data.length})` : typeof data);

            let users: Staff[] = [];
            if (Array.isArray(data)) {
                users = data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).data)) {
                users = (data as any).data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).users)) {
                users = (data as any).users;
            }

            // Client-side filtering to ensure accuracy (API might ignore param and return all users)
            return users.filter(user => {
                const uDeptId = user.department_id ||
                    (typeof user.department === 'object' && user.department ? (user.department as any)._id || (user.department as any).id : null);

                // If department is a string, it might be the ID or Name. 
                // We check against ID mostly.
                const uDeptString = typeof user.department === 'string' ? user.department : '';

                // Loose equality check for IDs (string vs likely string)
                return uDeptId == departmentId || uDeptString == departmentId;
            });
        } catch (e) {
            // Return empty array on error to allow other requests to proceed
            console.error(`Failed to fetch staff for department ${departmentId}`, e);
            return [];
        }
    },
    create: async (staffData: Partial<Staff>): Promise<any> => {
        try {
            const response = await api.post('api/auth/register', staffData);
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    update: async (id: string, staffData: Partial<Staff>): Promise<any> => {
        try {
            console.log(`Updating staff at path: api/auth/update/${id}`);
            const response = await api.put(`api/auth/update/${id}`, staffData);
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    delete: async (id: string): Promise<any> => {
        try {
            const response = await api.delete(`api/auth/${id}`);
            return response.data;
        } catch (e) {
            throw e;
        }
    },
};

export const attendanceApi = {
    getAll: async (): Promise<any> => {
        try {
            const response = await api.get('api/attendance/status');
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    getByStaffId: async (staffId: string): Promise<any> => {
        try {
            // Trying query parameter as path segment caused 404
            const response = await api.get(`api/attendance/status?staffId=${staffId}`);
            return response.data;
        } catch (e) {
            // Fallback to userId if staffId fails, or just throw
            throw e;
        }
    },
    clockIn: async (userId: string): Promise<any> => {
        try {
            const response = await api.post('api/attendance/clock-in', { userId });
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    clockOut: async (userId: string): Promise<any> => {
        try {
            const response = await api.post('api/attendance/clock-out', { userId });
            return response.data;
        } catch (e) {
            throw e;
        }
    },
};

export const ticketApi = {
    getAll: async (): Promise<any> => {
        try {
            const response = await api.get('api/tickets');
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    create: async (ticketData: Partial<Ticket>): Promise<any> => {
        try {
            const response = await api.post('api/tickets', ticketData);
            return response.data;
        } catch (e) {
            throw e;
        }
    },
};

export const lookupApi = {
    getRoles: async (): Promise<Role[]> => {
        try {
            const response = await api.get('api/lookups/roles');
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    getDepartments: async (): Promise<Department[]> => {
        try {
            const response = await api.get('api/departments');
            const data = response.data;
            if (Array.isArray(data)) {
                return data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).data)) {
                return (data as any).data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).departments)) {
                return (data as any).departments;
            }
            return [];
        } catch (e) {
            throw e;
        }
    },
};

export const departmentApi = {
    create: async (departmentData: Partial<Department>): Promise<any> => {
        try {
            console.log('Creating department with data:', departmentData);
            const response = await api.post('api/departments', departmentData);
            console.log('Department created successfully:', response.data);
            return response.data;
        } catch (e: any) {
            console.error('Failed to create department:', e);
            if (e.response) {
                console.error('Error response:', {
                    status: e.response.status,
                    data: e.response.data,
                    headers: e.response.headers
                });
            }
            throw e;
        }
    },
    getAll: async (): Promise<Department[]> => {
        try {
            const response = await api.get('api/departments');
            const data = response.data;
            if (Array.isArray(data)) {
                return data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).data)) {
                return (data as any).data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).departments)) {
                return (data as any).departments;
            }
            return [];
        } catch (e) {
            throw e;
        }
    },
    getById: async (id: string): Promise<Department> => {
        try {
            const response = await api.get(`api/departments/${id}`);
            const data = response.data;
            if (data && typeof data === 'object' && data.data) {
                return data.data;
            } else if (data && typeof data === 'object' && data.department) {
                return data.department;
            }
            return data;
        } catch (e) {
            throw e;
        }
    }
};

export const companyApi = {
    create: async (companyData: Partial<Company> | FormData): Promise<any> => {
        try {
            const isFormData = typeof window !== 'undefined' && companyData instanceof FormData;
            const response = await api.post('api/companies', companyData, {
                headers: isFormData ? { 'Content-Type': undefined } : {}
            });
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    getAll: async (): Promise<Company[]> => {
        try {
            const response = await api.get('api/companies');
            const data = response.data;
            if (Array.isArray(data)) {
                return data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).data)) {
                return (data as any).data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).companies)) {
                return (data as any).companies;
            }
            return [];
        } catch (e) {
            throw e;
        }
    },
    getEmployees: async (companyId: string): Promise<Staff[]> => {
        try {
            const response = await api.get(`api/companies/${companyId}/employees`);
            const data = response.data;
            if (Array.isArray(data)) {
                return data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).data)) {
                return (data as any).data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).employees)) {
                return (data as any).employees;
            }
            return [];
        } catch (e) {
            console.error('Failed to fetch company employees:', e);
            return [];
        }
    },
    delete: async (id: string): Promise<any> => {
        try {
            const response = await api.delete(`api/companies/${id}`);
            return response.data;
        } catch (e) {
            throw e;
        }
    }
};

export const branchApi = {
    create: async (branchData: Partial<Branch>): Promise<any> => {
        try {
            const response = await api.post('api/branches', branchData);
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    getAll: async (): Promise<Branch[]> => {
        try {
            const response = await api.get('api/branches');
            const data = response.data;
            if (Array.isArray(data)) {
                return data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).data)) {
                return (data as any).data;
            } else if (data && typeof data === 'object' && Array.isArray((data as any).branches)) {
                return (data as any).branches;
            }
            return [];
        } catch (e) {
            throw e;
        }
    },
    getById: async (id: string): Promise<Branch> => {
        try {
            const response = await api.get(`api/branches/${id}`);
            return response.data;
        } catch (e) {
            throw e;
        }
    },
    delete: async (id: string): Promise<any> => {
        try {
            const response = await api.delete(`api/branches/${id}`);
            return response.data;
        } catch (e) {
            throw e;
        }
    }
};


export const appraisalApi = {
    getMonthly: async (userId: string, month: string | number, year: string | number): Promise<Appraisal[]> => {
        try {
            const response = await api.get('api/appraisals/monthly', {
                params: {
                    month,
                    year,
                    userId
                }
            });
            const data = response.data;

            // Backend returns: { status: "success", data: { logs: [...], user: {...}, period: "...", totalLogs: N } }
            if (data?.status === 'success' && data.data?.logs && Array.isArray(data.data.logs)) {
                return data.data.logs;
            }

            // Fallback for direct array
            if (Array.isArray(data)) {
                return data as Appraisal[];
            }

            // Fallback for data.data being the array directly
            if (data?.data && Array.isArray(data.data)) {
                return data.data;
            }

            return [];
        } catch (e) {
            console.error('Failed to fetch appraisals:', e);
            throw e;
        }
    }
};

export default api;
